<#
.SYNOPSIS
    Vault content search engine - JSON index based keyword/tag/type search
.DESCRIPTION
    Searches vault_index.json generated by vault_index_build.ps1.
    Supports keyword, tag, type filtering with weighted ranking.
    Compact output mode for AI context injection.
.EXAMPLE
    .\vault_index_search.ps1 -Query "ECS"
    .\vault_index_search.ps1 -Tag "Unity" -Type "research"
    .\vault_index_search.ps1 -Query "sync" -Format compact -Top 5
#>

param(
    [string]$Query = "",
    [string]$Tag = "",
    [string]$Type = "",
    [ValidateSet('table','compact')]
    [string]$Format = 'table',
    [int]$Top = 10
)

$ErrorActionPreference = "Stop"

# Path auto-detect
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$VaultRoot = (Resolve-Path (Join-Path $ScriptDir "..\..")).Path
$DataDir = Join-Path $VaultRoot "_tools\data"
$IndexPath = Join-Path $DataDir "vault_index.json"

if (-not (Test-Path $IndexPath)) {
    Write-Host "[ERROR] Index not found: $IndexPath"
    Write-Host "Run vault_index_build.ps1 first."
    exit 1
}

# Load index
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$rawJson = [System.IO.File]::ReadAllText($IndexPath, $utf8NoBom)
$index = $rawJson | ConvertFrom-Json

$vaultName = $index.vault
$allNotes = @($index.notes)
$tagIndex = $index.tag_index

# Pre-filter
$filtered = $allNotes

if ($Tag) {
    $tagPaths = @()
    if ($tagIndex.PSObject.Properties.Name -contains $Tag) {
        $tagPaths = @($tagIndex.$Tag)
    }
    if ($tagPaths.Count -eq 0) {
        Write-Host "No notes found with tag: $Tag"
        exit 0
    }
    $filtered = @($filtered | Where-Object { $tagPaths -contains $_.path })
}

if ($Type) {
    $filtered = @($filtered | Where-Object { $_.type -eq $Type })
    if ($filtered.Count -eq 0) {
        Write-Host "No notes found with type: $Type"
        exit 0
    }
}

# Scoring function
function Get-NoteScore {
    param($note, [string[]]$keywords)
    $score = 0
    foreach ($q in $keywords) {
        $qLower = $q.ToLower()
        if ($note.title -and $note.title.ToLower().Contains($qLower)) {
            $score += 10
        }
        if ($note.tags) {
            foreach ($t in $note.tags) {
                $tLower = $t.ToLower()
                if ($tLower -eq $qLower) {
                    $score += 8
                } elseif ($tLower.Contains($qLower)) {
                    $score += 4
                }
            }
        }
        if ($note.headings) {
            foreach ($h in $note.headings) {
                if ($h.ToLower().Contains($qLower)) {
                    $score += 3
                    break
                }
            }
        }
        if ($note.summary -and $note.summary.ToLower().Contains($qLower)) {
            $score += 1
        }
    }
    return $score
}

# Search
$results = [System.Collections.ArrayList]@()

if ($Query) {
    $keywords = @($Query -split '\s+' | Where-Object { $_ })
    foreach ($note in $filtered) {
        $score = Get-NoteScore $note $keywords
        if ($score -gt 0) {
            $obj = [pscustomobject]@{ score = $score; note = $note }
            [void]$results.Add($obj)
        }
    }
    $results = @($results | Sort-Object -Property score -Descending)
} else {
    foreach ($note in $filtered) {
        $obj = [pscustomobject]@{ score = -1; note = $note }
        [void]$results.Add($obj)
    }
    $results = @($results | Sort-Object -Property @{Expression={$_.note.mtime}; Descending=$true})
}

# Limit
if ($results.Count -gt $Top) {
    $results = @($results[0..($Top - 1)])
}

if ($results.Count -eq 0) {
    Write-Host "No results found."
    exit 0
}

# Output
function Write-CompactOutput {
    param($resultList)
    foreach ($r in $resultList) {
        $n = $r.note
        $scoreStr = "[-]"
        if ($r.score -ge 0) { $scoreStr = "[$($r.score)]" }
        $tagsStr = ""
        if ($n.tags) { $tagsStr = ($n.tags -join ',') }
        Write-Host "$scoreStr $($n.title) | $($n.type) | tags:$tagsStr | $($n.path)"
        if ($n.summary) {
            Write-Host "  $($n.summary)"
        }
        Write-Host "---"
    }
}

function Write-TableOutput {
    param($resultList, $totalCount, $filteredCount, $vName, $qry, $tg, $tp)
    $queryStr = "(none)"
    if ($qry) { $queryStr = """$qry""" }
    $filterParts = @()
    if ($tg) { $filterParts += "tag=$tg" }
    if ($tp) { $filterParts += "type=$tp" }
    $filterDisplay = ""
    if ($filterParts.Count -gt 0) { $filterDisplay = " | Filter: $($filterParts -join ', ')" }

    Write-Host ""
    Write-Host "Vault: $vName | Notes: $totalCount | Query: $queryStr$filterDisplay"
    Write-Host ("=" * 70)

    $fmt = "{0,5}  {1,-10}  {2,-35}  {3}"
    Write-Host ($fmt -f "Score", "Type", "Title", "Path")
    Write-Host ($fmt -f "-----", "----", "-----", "----")

    foreach ($r in $resultList) {
        $n = $r.note
        $scoreStr = "-"
        if ($r.score -ge 0) { $scoreStr = "$($r.score)" }
        $titleTrunc = "$($n.title)"
        if ($titleTrunc.Length -gt 33) { $titleTrunc = $titleTrunc.Substring(0, 30) + "..." }
        $typeTrunc = "$($n.type)"
        if ($typeTrunc.Length -gt 10) { $typeTrunc = $typeTrunc.Substring(0, 10) }
        $pathTrunc = "$($n.path)"
        if ($pathTrunc.Length -gt 50) {
            $pathTrunc = "..." + $pathTrunc.Substring($pathTrunc.Length - 47)
        }
        Write-Host ($fmt -f $scoreStr, $typeTrunc, $titleTrunc, $pathTrunc)
    }

    Write-Host ("=" * 70)
    Write-Host "$($resultList.Count) results (from $filteredCount filtered, $totalCount total)"
}

if ($Format -eq 'compact') {
    Write-CompactOutput $results
} else {
    Write-TableOutput $results $allNotes.Count $filtered.Count $vaultName $Query $Tag $Type
}
