/**
 * clone_vault — Mirror-copy a vault to a new location.
 * Port of clone_vault.ps1 (172 LOC → ~100 LOC).
 *
 * Source selection precedence:
 *   1. --source-path <path>                          (explicit override)
 *   2. --hub <HubPath> + Hub's hub-marker.defaultTemplate
 *      → resolves to <BasicVaults>/<defaultTemplate> (sibling of the Hub)
 *   3. BasicContentsVault sibling of --hub (fallback if defaultTemplate missing
 *      or resolved path doesn't exist)
 *   4. CLI's own vault (auto-detect from script location)
 *
 * Post-copy: removes per-device configs, updates make-md systemName, writes
 * .sync/hub-source.json when --hub is specified.
 */

import { existsSync, readFileSync } from 'node:fs';
import { readdir, unlink, writeFile } from 'node:fs/promises';
import { join, resolve, relative, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mirrorDirectory } from '../lib/fs-mirror.js';
import { isHub, readHubMarker } from '../lib/hub-resolver.js';
import * as log from '../lib/logger.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Directories excluded from clone (new vault gets its own)
const CLONE_EXCLUDE_DIRS = ['.git', '.stfolder', 'smart-connections', 'cache', '.vault_data'];

// Per-vault volatile files Obsidian regenerates, plus BasicVaults-root
// launchers that are workspace-only tools (never belong in a cloned vault).
//   - workspace*.json / graph.json / backlink-in-document.json / .stignore
//       : regenerated by Obsidian / Syncthing per device
//   - MakeCloneVault.bat / .sh
//       : no-AI clone launchers meant to live only at Vaults/BasicVaults/
//         root. Satellites inherit them through mirror copy otherwise, where
//         their relative paths (`%~dp0..\..\BasicContentsVault`) break and
//         `--hub "%~dp0.."` falsely points at the satellite itself.
const CLONE_EXCLUDE_FILES = [
  'workspace.json', 'workspace-mobile.json', 'graph.json',
  'backlink-in-document.json', '.stignore',
  'MakeCloneVault.bat', 'MakeCloneVault.sh',
];

// Per-device plugin configs to remove after clone
const PER_DEVICE_CONFIGS = [
  '.obsidian/plugins/obsidian-git/data.json',
  '.obsidian/plugins/claudian/data.json',
];

/**
 * Resolve the effective clone source when --source-path is not given but
 * --hub is. Reads the Hub's hub-marker.json.defaultTemplate field and
 * resolves it as a sibling of the Hub (inside the same BasicVaults/ dir).
 *
 * @param {string} hubPath - Absolute Hub vault path
 * @param {object|null} hubMarker - Parsed hub-marker.json (may be null)
 * @returns {{ path: string, origin: string } | null}
 *          Resolved path + human-readable origin label, or null if no
 *          defaultTemplate specified.
 */
function resolveHubDefaultTemplate(hubPath, hubMarker) {
  const tmpl = hubMarker?.defaultTemplate;
  if (!tmpl) return null;

  // defaultTemplate can be either:
  //   - a bare name like "BasicDomainVault" (resolved as sibling of Hub)
  //   - a relative path like "../BasicDomainVault" (relative to Hub root)
  //   - an absolute path (used as-is)
  const hubParent = dirname(hubPath);
  const candidate = tmpl.includes('/') || tmpl.includes('\\') || /^[A-Za-z]:/.test(tmpl)
    ? resolve(hubPath, tmpl)
    : join(hubParent, tmpl);

  return { path: candidate, origin: `hub-marker.defaultTemplate="${tmpl}"` };
}

/**
 * Fallback to BasicContentsVault as a sibling of the given Hub.
 * Only used when --source-path and defaultTemplate are both missing/invalid.
 */
function resolveBasicContentsFallback(hubPath) {
  const hubParent = dirname(hubPath);
  const candidate = join(hubParent, 'BasicContentsVault');
  return existsSync(candidate)
    ? { path: candidate, origin: 'BasicContentsVault fallback (sibling of Hub)' }
    : null;
}

/**
 * @param {object} opts
 * @param {string} opts.targetPath - Destination path for new vault
 * @param {string} [opts.projectName] - Display name (defaults to folder name)
 * @param {string} [opts.sourcePath] - Source vault override. If omitted,
 *                                     source is resolved via --hub's
 *                                     defaultTemplate → BasicContentsVault
 *                                     fallback → CLI auto-detect.
 * @param {string} [opts.hub] - Hub vault root for the new satellite to bind to.
 *                              Auto-writes .sync/hub-source.json after clone.
 *                              If omitted, no hub-source.json is written (legacy scan).
 */
export async function cloneVault(opts) {
  if (!opts.targetPath) {
    log.error('--target-path is required.');
    process.exitCode = 1;
    return;
  }

  const targetPath = resolve(opts.targetPath);
  const projectName = opts.projectName || basename(targetPath);

  // Resolve hub binding target (if specified) — done BEFORE source resolution
  // so the Hub's defaultTemplate can inform source selection.
  let hubBindPath = null;
  let hubBindMarker = null;
  if (opts.hub) {
    hubBindPath = resolve(opts.hub);
    if (!isHub(hubBindPath)) {
      log.error(`--hub path is not a Hub (no .hub_marker / hub-marker.json): ${hubBindPath}`);
      process.exitCode = 1;
      return;
    }
    hubBindMarker = readHubMarker(hubBindPath);
  }

  // Source selection precedence (see file-level docstring):
  //   1. --source-path explicit
  //   2. Hub's defaultTemplate (sibling of Hub)
  //   3. BasicContentsVault sibling of Hub (fallback)
  //   4. CLI's own vault (auto-detect from script location — legacy)
  let sourceRoot;
  let sourceOrigin;
  if (opts.sourcePath) {
    sourceRoot = resolve(opts.sourcePath);
    sourceOrigin = '--source-path (explicit)';
  } else if (hubBindPath) {
    const fromDefault = resolveHubDefaultTemplate(hubBindPath, hubBindMarker);
    if (fromDefault && existsSync(fromDefault.path)) {
      sourceRoot = fromDefault.path;
      sourceOrigin = fromDefault.origin;
    } else {
      if (fromDefault) {
        log.warn(`defaultTemplate resolves to missing path: ${fromDefault.path} — falling back to BasicContentsVault`);
      }
      const fallback = resolveBasicContentsFallback(hubBindPath);
      if (!fallback) {
        log.error(`No source could be resolved: --hub specified but defaultTemplate missing/invalid and BasicContentsVault not found as sibling of ${hubBindPath}. Pass --source-path explicitly.`);
        process.exitCode = 1;
        return;
      }
      sourceRoot = fallback.path;
      sourceOrigin = fallback.origin;
    }
  } else {
    // Legacy: no --source-path, no --hub → CLI's own vault
    sourceRoot = resolve(__dirname, '..', '..', '..', '..', '..');
    sourceOrigin = 'CLI auto-detect (no --source-path, no --hub)';
  }

  log.info('====================================================');
  log.info(' Obsidian Vault Clone');
  log.info('====================================================');
  log.info(` Source : ${sourceRoot}`);
  log.info(`          (${sourceOrigin})`);
  log.info(` Target : ${targetPath}`);
  log.info(` Name   : ${projectName}`);
  if (hubBindPath) {
    log.info(` Hub    : ${hubBindPath} (${hubBindMarker?.hubId || '?'})`);
  }
  log.info('----------------------------------------------------');

  // Safety: prevent target inside source
  if (targetPath.startsWith(sourceRoot + '/') || targetPath.startsWith(sourceRoot + '\\')) {
    log.error('Target is inside source directory. This would cause infinite recursive copy.');
    process.exitCode = 1;
    return;
  }

  if (!existsSync(sourceRoot)) {
    log.error(`Source path not found: ${sourceRoot}`);
    process.exitCode = 1;
    return;
  }

  // Step 1: Mirror copy
  log.info('\n[1/4] Copying files...');
  try {
    const result = await mirrorDirectory(sourceRoot, targetPath, {
      excludeDirs: CLONE_EXCLUDE_DIRS,
      excludeFiles: CLONE_EXCLUDE_FILES,
      noPrune: true,  // Don't delete extra files in target
      log: (msg) => log.info(`  ${msg}`),
    });
    log.info(`  Copied: ${result.copied}, Unchanged: ${result.unchanged}`);
  } catch (err) {
    log.error(`Copy failed: ${err.message}`);
    process.exitCode = 1;
    return;
  }

  // Step 2: Remove per-device plugin configs
  log.info('\n[2/4] Removing per-device plugin configs...');
  for (const rel of PER_DEVICE_CONFIGS) {
    const filePath = join(targetPath, rel);
    if (existsSync(filePath)) {
      await unlink(filePath);
      log.info(`  - Removed: ${rel}`);
    }
  }

  // Step 3: Update make-md systemName
  log.info('\n[3/4] Updating plugin settings...');
  // (numbering unchanged — step 4 already used for hub-source.json)
  const makeMdPath = join(targetPath, '.obsidian', 'plugins', 'make-md', 'data.json');
  if (existsSync(makeMdPath)) {
    try {
      const content = readFileSync(makeMdPath, 'utf8');
      const updated = content.replace(/"systemName"\s*:\s*"[^"]*"/, `"systemName": "${projectName}"`);
      if (content !== updated) {
        await writeFile(makeMdPath, updated, 'utf8');
        log.info(`  - make-md systemName -> ${projectName} [OK]`);
      } else {
        log.info('  - make-md systemName: already up to date');
      }
    } catch (err) {
      log.warn(`  Could not update make-md: ${err.message}`);
    }
  } else {
    log.info('  - make-md plugin not found, skipping');
  }

  // Step 4: Write hub-source.json if --hub specified
  log.info('\n[4/4] Writing hub-source.json...');
  if (hubBindPath) {
    const relHub = relative(targetPath, hubBindPath).split(/[/\\]/).join('/');
    const hubSource = {
      hubPath: relHub || '.',
      hubId: hubBindMarker?.hubId || opts.hubId || 'core',
      bindAt: new Date().toISOString().slice(0, 10),
    };
    const hubSourcePath = join(targetPath, '.sync', 'hub-source.json');
    await writeFile(hubSourcePath, JSON.stringify(hubSource, null, 2) + '\n', 'utf8');
    log.info(`  - Wrote: .sync/hub-source.json (hubId="${hubSource.hubId}", hubPath="${hubSource.hubPath}")`);

    // Also clean stale .hub_marker if the clone source was a Hub but target is satellite
    const staleMarker = join(targetPath, '.sync', '.hub_marker');
    if (existsSync(staleMarker)) {
      await unlink(staleMarker);
      log.info(`  - Removed stale .hub_marker (cloned satellite is not a Hub)`);
    }
  } else {
    log.info('  - No --hub specified, skipping hub-source.json (legacy scan fallback will be used)');
  }

  log.info('\n====================================================');
  log.info(' DONE');
  log.info('====================================================');
  log.info(` Vault copied to : ${targetPath}`);
  log.info(` System name set : ${projectName}`);
  log.info('');
  log.info(' Next: Open Obsidian -> Manage vaults -> Open folder');
  log.info(`       Select: ${targetPath}`);
  log.info('====================================================');
}
